default:
  suites:
    default:
      contexts:
        - FeatureContext:
            kernel: "@kernel"
            em: "@doctrine.orm.default_entity_manager"
        - Behat\MinkExtension\Context\MinkContext
                - behatch:context:browser
                - behatch:context:debug
                - behatch:context:system
                - behatch:context:json
                - behatch:context:table
                - behatch:context:rest
                - behatch:context:xml
  extensions:
    FriendsOfBehat\SymfonyExtension:
      kernel:
       bootstrap: tests/bootstrap.php
       class: App\Kernel
    Behatch\Extension : ~
    Behat\MinkExtension :
      base_url : "http://127.0.0.1:8000"
          sessions:
            default:
              symfony2: ~

                  

